#ifndef __TIKI_VISUALIZATION_SHADER_HPP_INCLUDED__
#define __TIKI_VISUALIZATION_SHADER_HPP_INCLUDED__

#include "tiki/graphics/graphicstypes.hpp"

TIKI_GRAPHICS_NAMESPACE_BEGIN

#define TIKI_VISUALIZATION_MODE_DIFFUSE				0
#define TIKI_VISUALIZATION_MODE_SELFILLUMINATION	1
#define TIKI_VISUALIZATION_MODE_NORMAL				2

TIKI_GRAPHICS_NAMESPACE_END

#endif // __TIKI_VISUALIZATION_SHADER_HPP_INCLUDED__
