
set(BUILDTOOLS_SCRIPTS library/buildtools/cmake/scripts)

add_definitions(-DUNICODE -D_UNICODE)

if(CMAKE_CONFIGURATION_TYPES)
  set(CMAKE_CONFIGURATION_TYPES Debug Release Master)
  set(CMAKE_CONFIGURATION_TYPES "${CMAKE_CONFIGURATION_TYPES}" CACHE STRING "Reset the configurations to what we need" FORCE)
endif()

SET(CMAKE_CXX_FLAGS_MASTER ${CMAKE_CXX_FLAGS_RELEASE})
SET(CMAKE_EXE_LINKER_FLAGS_MASTER ${CMAKE_EXE_LINKER_FLAGS_RELEASE})

if (NOT DEFINED TIKI_PLATFORM)
  set(TIKI_PLATFORM "Windows")
endif()
