name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build Assets
      run: .\build_assets.ps1
      shell: powershell
    - name: Build Code
      run: .\build_code.ps1
      shell: powershell
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
